
export type Abbreviation = {
    term: string;
    definition: string;
};

export const medicalAbbreviations: Abbreviation[] = [
    { term: '1°', definition: 'primary, first degree' },
    { term: 'a', definition: 'before' },
    { term: 'AED', definition: 'Automated External Defibrillator' },
    { term: 'AOX3', definition: 'alert and oriented to person, place, and time' },
    { term: 'Abd', definition: 'abdomen' },
    { term: 'Ab', definition: 'abortion' },
    { term: 'ac', definition: 'antecubital' },
    { term: 'AF', definition: 'atrial fibrillation' },
    { term: 'ARDS', definition: 'Adult Respiratory Distress Syndrome' },
    { term: 'AT', definition: 'atrial tachycardia' },
    { term: 'AV', definition: 'atrioventricular' },
    { term: 'b.i.d.', definition: 'twice a day' },
    { term: 'BSA', definition: 'body surface area' },
    { term: 'BS', definition: 'blood sugar and/or breath sounds' },
    { term: 'c', definition: 'with' },
    { term: 'CC or C/C', definition: 'chief complaint' },
    { term: 'CHF', definition: 'Congestive Heart Failure' },
    { term: 'CNS', definition: 'Central Nervous System' },
    { term: 'c/o', definition: 'complains of' },
    { term: 'CO', definition: 'carbon monoxide' },
    { term: 'CO2', definition: 'carbon dioxide' },
    { term: 'D/C', definition: 'discontinue' },
    { term: 'DM', definition: 'diabetes mellitus' },
    { term: 'DTs', definition: 'delirium tremens' },
    { term: 'DVT', definition: 'deep venous thrombosis' },
    { term: 'Dx', definition: 'diagnosis' },
    { term: 'EDC', definition: 'estimated date of confinement' },
    { term: 'EKG', definition: 'Electrocardiogram' },
    { term: 'EJ', definition: 'external jugular' },
    { term: 'ENT', definition: 'ear, nose, and throat' },
    { term: 'ETOH', definition: 'abbreviation of Ethanol (grain alcohol)' },
    { term: 'Fl', definition: 'fluid' },
    { term: 'Fx', definition: 'fracture' },
    { term: 'GB', definition: 'gall bladder' },
    { term: 'g or gm', definition: 'gram' },
    { term: 'gr.', definition: 'grain' },
    { term: 'GSW', definition: 'gunshot wound' },
    { term: 'gtt', definition: 'drop' },
    { term: 'GU', definition: 'genitourinary' },
    { term: 'GYN', definition: 'gynecologic' },
    { term: 'h or hr', definition: 'hour' },
    { term: 'H/A', definition: 'headache' },
    { term: 'Hg', definition: 'mercury' },
    { term: 'H&P', definition: 'history and physical' },
    { term: 'Hx', definition: 'history' },
    { term: 'ICP', definition: 'intracranial pressure' },
    { term: 'JVD', definition: 'jugular venous distension' },
    { term: 'KVO', definition: 'keep vein open' },
    { term: 'LAC', definition: 'laceration' },
    { term: 'LBBB', definition: 'left bundle branch block' },
    { term: 'MAEW', definition: 'moves all extremities well' },
    { term: 'NaCl', definition: 'sodium chloride' },
    { term: 'NAD', definition: 'no apparent distress/ no acute distress' },
    { term: 'NKA', definition: 'no known allergies' },
    { term: 'NPO', definition: 'nothing by mouth' },
    { term: 'OD', definition: 'overdose' },
    { term: 'O.D.', definition: 'right eye' },
    { term: 'O.S.', definition: 'left eye' },
    { term: 'PERL', definition: 'pupils equal and reactive to light' },
    { term: 'PID', definition: 'pelvic inflammatory disease' },
    { term: 'p.o.', definition: 'by mouth' },
    { term: 'PTA', definition: 'prior to arrival' },
    { term: 'Pt', definition: 'patient' },
    { term: 'q', definition: 'every' },
    { term: 'qh', definition: 'every hour' },
    { term: 'q.i.d.', definition: 'four times a day' },
    { term: 'RBBB', definition: 'right bundle branch block' },
    { term: 'R/O', definition: 'rule out' },
    { term: 'ROM', definition: 'range of motion' },
    { term: 'Rx', definition: 'prescription' },
    { term: 's', definition: 'without' },
    { term: 'S/S', definition: 'signs and symptoms' },
    { term: 'TIA', definition: 'transient ischemic attack' },
    { term: 't.i.d.', definition: 'three times a day' },
    { term: 'Tx', definition: 'treatment' },
    { term: 'V.S.', definition: 'vital signs' },
    { term: 'y.o.', definition: 'years old' },
];
