/**
 * Source data for NASEMSO V3 national baseline JSON.
 * Run: npx tsx scripts/build-national-baseline.ts
 */
export type L = 'EMR' | 'EMT' | 'AEMT' | 'PARAMEDIC';
export type R = 'IV' | 'IO' | 'IM' | 'IN' | 'PO' | 'SL' | 'NEB';
export type Cat = 'Airway' | 'Cardiac' | 'Pharmacology' | 'Trauma' | 'Medical';

export type MedRow = {
  id: string;
  name: string;
  minLevel: L;
  ind: string[];
  contra: string[];
  routes: R[];
  adult: string;
  pediatric: string;
  maxDose?: string;
  concentration?: string;
};

export type ProcRow = {
  id: string;
  name: string;
  category: Cat;
  minLevel: L;
  ind: string[];
  contra: string[];
  equipment: string[];
  parameters?: string;
  success: string;
};

/** Appendix III monographs → normalized grader phrases + protocol-linked dosing where cited in NASEMSO V3 extract. */
export const MEDICATIONS: MedRow[] = [
  {
    id: 'MED_ACETAZOLAMIDE',
    name: 'Acetazolamide',
    minLevel: 'PARAMEDIC',
    ind: ['Acute mountain sickness'],
    contra: ['Hypokalemia', 'Hyponatremia', 'Sulfa allergy', 'Severe liver or renal disease', 'Angle-closure glaucoma'],
    routes: ['IV', 'PO'],
    adult: 'Per altitude illness / toxinology protocol',
    pediatric: 'Per protocol; weight-based',
  },
  {
    id: 'MED_ACETAMINOPHEN',
    name: 'Acetaminophen',
    minLevel: 'EMT',
    ind: ['Pain', 'Fever'],
    contra: ['Acetaminophen allergy', 'Severe acute liver disease'],
    routes: ['PO'],
    adult: '650–1000 mg PO per protocol',
    pediatric: '15 mg/kg PO per protocol (max per local guideline)',
  },
  {
    id: 'MED_ACETIC_ACID',
    name: 'Acetic acid (vinegar)',
    minLevel: 'EMT',
    ind: ['Jellyfish envenomation pain (non-US species)'],
    contra: ['US jellyfish envenomation—may worsen discharge'],
    routes: ['PO'],
    adult: 'Topical/acetic acid irrigation per envenomation protocol',
    pediatric: 'Per toxinology protocol',
  },
  {
    id: 'MED_ACETYLCYSTEINE',
    name: 'Acetylcysteine',
    minLevel: 'PARAMEDIC',
    ind: ['Acetaminophen overdose / suspected hepatotoxicity'],
    contra: ['Acute asthma (relative)'],
    routes: ['IV', 'PO'],
    adult: 'Per regional poison center protocol (AC loading/maintenance)',
    pediatric: 'Per poison center; weight-based',
    maxDose: 'Per poison center',
  },
  {
    id: 'MED_ACTIVATED_CHARCOAL',
    name: 'Activated Charcoal',
    minLevel: 'AEMT',
    ind: ['Toxic ingestion (appropriate substances)'],
    contra: ['Unprotected airway', 'Caustic ingestion', 'Bowel obstruction', 'Relative: sorbitol no longer co-administered'],
    routes: ['PO'],
    adult: '1 g/kg PO (usual adult dose 50–100 g) per poisoning protocol',
    pediatric: '1 g/kg PO per poisoning protocol',
  },
  {
    id: 'MED_ADENOSINE',
    name: 'Adenosine',
    minLevel: 'PARAMEDIC',
    ind: ['Stable regular narrow-complex SVT', 'Regular monomorphic wide-complex tachycardia when indicated'],
    contra: ['Second- or third-degree AV block (without pacemaker)', 'Sick sinus syndrome', 'Asthmatic VT', 'Atrial flutter/fibrillation for termination', 'Polymorphic VT'],
    routes: ['IV'],
    adult: '6 mg IV rapid push with NS flush (e.g. 10–20 mL); then 12 mg with flush if needed per tachycardia protocol',
    pediatric: '0.1 mg/kg IV rapid push with NS flush (first dose max 6 mg); subsequent 0.2 mg/kg with flush per protocol (max per guideline)',
    concentration: '3 mg/mL (typical vial dilution per agency)',
  },
  {
    id: 'MED_ALBUTEROL',
    name: 'Albuterol',
    minLevel: 'EMT',
    ind: ['Bronchospasm', 'Anaphylaxis with bronchospasm', 'Asthma', 'COPD exacerbation'],
    contra: ['Hypersensitivity', 'Tachycardia from structural heart disease (relative)'],
    routes: ['NEB'],
    adult: '2.5–5 mg nebulized',
    pediatric: '2.5–5 mg nebulized per guideline',
  },
  {
    id: 'MED_AMIODARONE',
    name: 'Amiodarone',
    minLevel: 'PARAMEDIC',
    ind: ['Stable wide-complex tachycardia', 'VF/pulseless VT refractory to CPR/shock/epinephrine', 'Atrial fibrillation rate control when indicated'],
    contra: ['Hypersensitivity', 'Severe sinus node dysfunction', 'High-grade AV block without pacemaker', 'Bradycardic syncope without pacemaker', 'Cardiogenic shock'],
    routes: ['IV'],
    adult: 'Stable: 150 mg IV over 10 min; cardiac arrest: 300 mg IV/IO (may consider 150 mg repeat); infusion per post-ROSC care',
    pediatric: '5 mg/kg IV/IO (max 300 mg) for VF/pulseless VT per arrest protocol',
    maxDose: '300 mg bolus (arrest); 150 mg for stable wide-complex',
  },
  {
    id: 'MED_AMYL_NITRITE',
    name: 'Amyl Nitrite',
    minLevel: 'PARAMEDIC',
    ind: ['Suspected cyanide poisoning (kit adjunct)'],
    contra: ['Smoke inhalation with suspected CO poisoning', 'Hypersensitivity'],
    routes: ['IN'],
    adult: 'Per cyanide antidote kit / protocol',
    pediatric: 'Per cyanide kit protocol',
  },
  {
    id: 'MED_ASA',
    name: 'Aspirin',
    minLevel: 'EMT',
    ind: ['Suspected ACS'],
    contra: ['ASA/NSAID hypersensitivity', 'Active GI bleed', 'Bleeding diathesis', 'Pediatric viral illness (relative)'],
    routes: ['PO'],
    adult: '162–325 mg chewable PO (non–enteric-coated preferred)',
    pediatric: 'Not routinely for ACS in pediatrics—per protocol',
  },
  {
    id: 'MED_ATROPINE',
    name: 'Atropine',
    minLevel: 'PARAMEDIC',
    ind: ['Symptomatic bradycardia', 'Organophosphate/nerve agent toxicity'],
    contra: ['None for ACLS tox scenarios (relative glaucoma, obstruction)'],
    routes: ['IV', 'IO', 'IM'],
    adult: 'Bradycardia: 1 mg IV q3–5min (max 3 mg) per bradycardia protocol',
    pediatric: '0.02 mg/kg IV/IO (single dose min 0.1 mg, max child dose 0.5 mg) q5min per protocol',
    maxDose: 'Adult max 3 mg bradycardia',
  },
  {
    id: 'MED_CALCIUM_CHLORIDE',
    name: 'Calcium Chloride',
    minLevel: 'PARAMEDIC',
    ind: ['Hyperkalemia with ECG changes', 'Calcium channel blocker overdose', 'HF acid skin burn (adjunct)'],
    contra: ['Hypercalcemia', 'Digitalis toxicity (relative)', 'Extravasation risk'],
    routes: ['IV'],
    adult: '1 g slow IV (10% solution) for hyperkalemia/CCB OD per protocol; pediatrics 20 mg/kg (0.2 mL/kg)',
    pediatric: '20 mg/kg IV (0.2 mL/kg of 10%) slow per protocol',
  },
  {
    id: 'MED_CALCIUM_GLUCONATE',
    name: 'Calcium Gluconate',
    minLevel: 'PARAMEDIC',
    ind: ['Hyperkalemia with ECG changes', 'Calcium channel blocker overdose', 'HF acid exposure protocol'],
    contra: ['Hypercalcemia', 'Digitalis toxicity (relative)'],
    routes: ['IV'],
    adult: '1 g IV slow over 2 min; pediatrics 100 mg/kg (1 mL/kg of 10%)',
    pediatric: '100 mg/kg IV (1 mL/kg 10%) slow; may repeat per protocol',
  },
  {
    id: 'MED_CIMETIDINE',
    name: 'Cimetidine',
    minLevel: 'PARAMEDIC',
    ind: ['Allergic reaction adjunct (H2 blocker)'],
    contra: ['Cimetidine hypersensitivity'],
    routes: ['IV', 'PO'],
    adult: 'Per allergic reaction protocol (adjunct to diphenhydramine)',
    pediatric: 'Per protocol',
  },
  {
    id: 'MED_DEXAMETHASONE',
    name: 'Dexamethasone',
    minLevel: 'AEMT',
    ind: ['Croup', 'Bronchospasm', 'High-altitude cerebral edema'],
    contra: ['Systemic fungal infection', 'Cerebral malaria'],
    routes: ['IV', 'IM'],
    adult: '0.1–0.6 mg/kg per croup/asthma protocol (agency-specific)',
    pediatric: '0.15–0.6 mg/kg IM/IV for croup per guideline',
  },
  {
    id: 'MED_DEXTROSE_10',
    name: 'Dextrose 10%',
    minLevel: 'AEMT',
    ind: ['Hypoglycemia'],
    contra: ['Hyperglycemia', 'Intracranial hemorrhage (relative)'],
    routes: ['IV', 'IO'],
    adult: 'D10 infusion or incremental boluses until mental status improves per hypoglycemia protocol',
    pediatric: 'D10 preferred all ages—incremental boluses per protocol (e.g. 5 mL/kg)',
    concentration: '10% dextrose',
  },
  {
    id: 'MED_DEXTROSE_50',
    name: 'Dextrose 50%',
    minLevel: 'AEMT',
    ind: ['Hypoglycemia when D10 not carried'],
    contra: ['Extravasation risk', 'Hyperglycemia'],
    routes: ['IV', 'IO'],
    adult: '25–50 mL slow IV (typical) per hypoglycemia protocol',
    pediatric: 'Avoid D50 in pediatrics—use D10 per guideline',
    concentration: '50% dextrose',
  },
  {
    id: 'MED_DIAZEPAM',
    name: 'Diazepam',
    minLevel: 'PARAMEDIC',
    ind: ['Seizure', 'Agitated violent patient', 'Skeletal muscle relaxation'],
    contra: ['Severe respiratory depression'],
    routes: ['IV', 'IO', 'IM', 'PO'],
    adult: '5–10 mg IV per seizure/behavioral protocol',
    pediatric: '0.2–0.3 mg/kg IV (max per protocol) for seizures',
  },
  {
    id: 'MED_DILTIAZEM',
    name: 'Diltiazem',
    minLevel: 'PARAMEDIC',
    ind: ['Stable narrow-complex SVT / rapid AF with RVR when appropriate'],
    contra: ['Hypotension SBP <90', 'WPW with AF', 'High-grade AV block without pacemaker', 'Acute MI (relative)'],
    routes: ['IV'],
    adult: '0.25 mg/kg IV over 2 minutes (repeat 0.35 mg/kg in 15 min per protocol)',
    pediatric: 'Not first-line in pediatrics—per medical direction',
    maxDose: 'typically adult bolus caps per agency',
  },
  {
    id: 'MED_DIPHENHYDRAMINE',
    name: 'Diphenhydramine',
    minLevel: 'EMT',
    ind: ['Allergic reaction urticaria', 'Anaphylaxis adjunct', 'Dystonic reaction'],
    contra: ['Diphenhydramine hypersensitivity', 'Acute asthma (controversial)'],
    routes: ['IV', 'IM', 'PO'],
    adult: '25–50 mg IV/IM/PO per anaphylaxis protocol',
    pediatric: '1 mg/kg IM/IV/PO (max 50 mg)',
  },
  {
    id: 'MED_DOPAMINE',
    name: 'Dopamine',
    minLevel: 'PARAMEDIC',
    ind: ['Shock with hypotension after volume'],
    contra: ['Pheochromocytoma', 'VF', 'Uncorrected tachyarrhythmia'],
    routes: ['IV'],
    adult: '2–20 mcg/kg/min IV infusion titrate to MAP per shock protocol',
    pediatric: '2–20 mcg/kg/min IV per shock protocol',
  },
  {
    id: 'MED_DROPERIDOL',
    name: 'Droperidol',
    minLevel: 'PARAMEDIC',
    ind: ['Acute psychosis / severe agitation'],
    contra: ['Prolonged QT', 'Hypersensitivity'],
    routes: ['IV', 'IM'],
    adult: 'Low-dose IM/IV per behavioral emergency protocol (monitor ECG)',
    pediatric: 'Per medical direction',
  },
  {
    id: 'MED_EPI_1_1000',
    name: 'Epinephrine (1 mg/mL)',
    minLevel: 'EMT',
    ind: ['Anaphylaxis', 'Bronchospasm with wheeze (nebulized)', 'Stridor (nebulized epinephrine)'],
    contra: ['None in life-threatening anaphylaxis'],
    routes: ['IM', 'NEB'],
    adult: 'Anaphylaxis: 0.3 mg IM lateral thigh; Neb: 5 mL of 1 mg/mL nebulized',
    pediatric: 'Anaphylaxis: 0.15 mg IM (<25 kg); Neb: per protocol',
    concentration: '1 mg/mL',
  },
  {
    id: 'MED_EPI_1_10000',
    name: 'Epinephrine (0.1 mg/mL)',
    minLevel: 'PARAMEDIC',
    ind: ['Cardiac arrest', 'Push-dose vasopressor', 'Post-resuscitation shock', 'Severe anaphylaxis IV drip after IM failures'],
    contra: ['None in cardiac arrest'],
    routes: ['IV', 'IO'],
    adult: 'Arrest (adult ACLS): 1 mg IV/IO as soon as IV/IO access is established, then q3–5min; push-dose: 1 mL of 0.1 mg/mL in 9 mL NS then 0.01 mg/kg boluses per perfusion protocol',
    pediatric: 'Arrest: 0.01 mg/kg IV/IO (0.1 mL/kg of 0.1 mg/mL) q3–5min once access available; max per guideline',
    concentration: '0.1 mg/mL',
  },
  {
    id: 'MED_FAMOTIDINE',
    name: 'Famotidine',
    minLevel: 'PARAMEDIC',
    ind: ['Allergic reaction adjunct (H2 blocker)'],
    contra: ['Famotidine hypersensitivity'],
    routes: ['IV', 'PO'],
    adult: '20 mg IV per anaphylaxis adjunct protocol',
    pediatric: 'Per protocol',
  },
  {
    id: 'MED_FENTANYL',
    name: 'Fentanyl',
    minLevel: 'PARAMEDIC',
    ind: ['Severe acute pain'],
    contra: ['Hypersensitivity', 'Severe respiratory depression risk'],
    routes: ['IV', 'IN', 'IM'],
    adult: '25–100 mcg slow IV titrated per pain protocol',
    pediatric: '1–2 mcg/kg slow IV per pain protocol (max per agency)',
  },
  {
    id: 'MED_GLUCAGON',
    name: 'Glucagon',
    minLevel: 'EMT',
    ind: ['Hypoglycemia (no IV access)', 'Beta-blocker / CCB overdose bradycardia'],
    contra: ['Pheochromocytoma', 'Insulinoma'],
    routes: ['IM', 'IN', 'IV'],
    adult: 'Hypoglycemia: 1 unit IM; BB/CCB OD: 5 mg IV bolus then repeat per guideline',
    pediatric: 'Hypoglycemia 0.5–1 mg IM; BB/CCB: 0.05 mg/kg IV boluses per tox protocol',
  },
  {
    id: 'MED_HALOPERIDOL',
    name: 'Haloperidol',
    minLevel: 'PARAMEDIC',
    ind: ['Acute psychosis', 'Violent agitation refractory to de-escalation'],
    contra: ['NMS', 'Parkinson disease', 'Coma', 'Severe CNS depression'],
    routes: ['IV', 'IM'],
    adult: '2–5 mg IM/IV per behavioral protocol (monitor QT)',
    pediatric: 'Per medical direction',
  },
  {
    id: 'MED_HELIOX',
    name: 'Heliox (helium-oxygen)',
    minLevel: 'PARAMEDIC',
    ind: ['Severe bronchospasm refractory to standard care', 'Pediatric croup refractory'],
    contra: ['None'],
    routes: ['NEB'],
    adult: 'Heliox via tight-fitting mask / neb per respiratory distress protocol',
    pediatric: 'Same',
  },
  {
    id: 'MED_HYDRALAZINE',
    name: 'Hydralazine',
    minLevel: 'PARAMEDIC',
    ind: ['Severe hypertension with pre-eclampsia features'],
    contra: ['Coronary artery disease', 'Hypersensitivity'],
    routes: ['IV', 'IM'],
    adult: '5–10 mg IV slow per OB emergency protocol',
    pediatric: 'Per medical direction',
  },
  {
    id: 'MED_HYDROCORTISONE',
    name: 'Hydrocortisone succinate',
    minLevel: 'PARAMEDIC',
    ind: ['Adrenal insufficiency crisis', 'Severe asthma adjunct'],
    contra: ['Untreated systemic infection (relative)'],
    routes: ['IV', 'IM'],
    adult: '100 mg IV bolus per adrenal crisis protocol',
    pediatric: '2 mg/kg IV per protocol',
  },
  {
    id: 'MED_HYDROMORPHONE',
    name: 'Hydromorphone',
    minLevel: 'PARAMEDIC',
    ind: ['Acute severe pain'],
    contra: ['Hypersensitivity', 'Severe respiratory depression'],
    routes: ['IV', 'IM'],
    adult: '0.5–2 mg slow IV titrate per pain protocol',
    pediatric: 'Per weight protocol',
  },
  {
    id: 'MED_HYDROXOCOBALAMIN',
    name: 'Hydroxocobalamin',
    minLevel: 'PARAMEDIC',
    ind: ['Cyanide poisoning'],
    contra: ['Hypersensitivity'],
    routes: ['IV'],
    adult: '5 g IV over 15 min (kit dosing) per cyanide protocol',
    pediatric: '70 mg/kg IV per kit (max 5 g)',
  },
  {
    id: 'MED_IBUPROFEN',
    name: 'Ibuprofen',
    minLevel: 'EMT',
    ind: ['Pain', 'Fever'],
    contra: ['Aspirin allergy', 'Active bleeding', 'Third-trimester pregnancy'],
    routes: ['PO'],
    adult: '400–600 mg PO',
    pediatric: '10 mg/kg PO per protocol',
  },
  {
    id: 'MED_IPRATROPIUM',
    name: 'Ipratropium',
    minLevel: 'AEMT',
    ind: ['Asthma', 'COPD exacerbation'],
    contra: ['Hypersensitivity to ipratropium/atropine'],
    routes: ['NEB'],
    adult: '0.5 mg neb mixed with albuterol',
    pediatric: '0.25–0.5 mg neb per guideline',
  },
  {
    id: 'MED_ISOPROPYL_ALCOHOL',
    name: 'Isopropyl alcohol',
    minLevel: 'EMT',
    ind: ['Nausea (inhaled topical technique—rare)'],
    contra: ['None'],
    routes: ['IN'],
    adult: 'Not routine; per nausea protocol',
    pediatric: 'Avoid',
  },
  {
    id: 'MED_KETAMINE',
    name: 'Ketamine',
    minLevel: 'PARAMEDIC',
    ind: ['Severe agitation', 'Pain (dissociative dosing)', 'RSI adjunct per protocol'],
    contra: ['Hypersensitivity'],
    routes: ['IV', 'IM', 'IN'],
    adult: '1–2 mg/kg IV or 4–5 mg/kg IM for sedation per protocol',
    pediatric: '1–1.5 mg/kg IV; 3–5 mg/kg IM',
  },
  {
    id: 'MED_KETOROLAC',
    name: 'Ketorolac',
    minLevel: 'PARAMEDIC',
    ind: ['Moderate–severe pain when NSAID appropriate'],
    contra: ['Active GI bleed', 'Renal failure', 'Bleeding disorder', 'Third trimester'],
    routes: ['IV', 'IM'],
    adult: '15–30 mg IV/IM (max daily per policy)',
    pediatric: '0.5 mg/kg IV/IM (max 15 mg) per protocol',
    maxDose: 'Agency max daily dose',
  },
  {
    id: 'MED_LABETALOL',
    name: 'Labetalol',
    minLevel: 'PARAMEDIC',
    ind: ['Severe hypertension pre-eclampsia', 'Aortic dissection adjunct (when ordered)'],
    contra: ['Asthma', 'Bradycardia', 'Heart block without pacemaker'],
    routes: ['IV'],
    adult: '10–20 mg IV slow; double dose q10min per severe hypertension protocol',
    pediatric: 'Per medical direction',
  },
  {
    id: 'MED_LIDOCAINE',
    name: 'Lidocaine',
    minLevel: 'PARAMEDIC',
    ind: ['VF/pulseless VT alternative to amiodarone', 'Stable wide-complex VT (rare—per ACLS-trained protocols)'],
    contra: ['Hypersensitivity to amide anesthetics', 'High-grade blocks without pacemaker'],
    routes: ['IV', 'IO'],
    adult: 'Arrest: 1–1.5 mg/kg IV; repeat 0.5–0.75 mg/kg',
    pediatric: '1 mg/kg IV/IO load per arrest',
    maxDose: '3 mg/kg single course approx',
  },
  {
    id: 'MED_LORAZEPAM',
    name: 'Lorazepam',
    minLevel: 'PARAMEDIC',
    ind: ['Status epilepticus', 'Agitation', 'Hypothermia shivering'],
    contra: ['Severe respiratory depression', 'Acute narrow-angle glaucoma'],
    routes: ['IV', 'IO', 'IM'],
    adult: '0.1 mg/kg IV (max 4 mg) per seizure protocol',
    pediatric: '0.1 mg/kg IV/IO (max 4 mg)',
  },
  {
    id: 'MED_MAGNESIUM_SULFATE',
    name: 'Magnesium sulfate',
    minLevel: 'PARAMEDIC',
    ind: ['Torsades de pointes', 'Refractory bronchospasm', 'Eclampsia / pre-eclampsia seizure'],
    contra: ['Hypermagnesemia', 'Heart block', 'Myocardial damage (relative)'],
    routes: ['IV'],
    adult: 'Torsades: 2 g IV over 1–2 min; OB: 4 g load per eclampsia protocol; bronchospasm: 2 g IV over 20 min',
    pediatric: 'Torsades 25–50 mg/kg; asthma 40 mg/kg max 2 g over 15–30 min per protocol',
  },
  {
    id: 'MED_METHYLPREDNISOLONE',
    name: 'Methylprednisolone',
    minLevel: 'PARAMEDIC',
    ind: ['Severe bronchospasm', 'Adrenal crisis', 'Spinal cord injury protocol (agency-specific)'],
    contra: ['Untreated infection (relative)', 'High-dose contraindicated TBI policy in some systems'],
    routes: ['IV', 'IM'],
    adult: '40–125 mg IV per asthma protocol',
    pediatric: '1–2 mg/kg IV (max 125 mg)',
  },
  {
    id: 'MED_METOCLOPRAMIDE',
    name: 'Metoclopramide',
    minLevel: 'PARAMEDIC',
    ind: ['Nausea and vomiting'],
    contra: ['GI hemorrhage', 'Mechanical obstruction', 'Seizure disorder'],
    routes: ['IV', 'IM'],
    adult: '10 mg IV slow',
    pediatric: '0.1 mg/kg IV (max 10 mg)',
  },
  {
    id: 'MED_METOPROLOL',
    name: 'Metoprolol',
    minLevel: 'PARAMEDIC',
    ind: ['Stable narrow-complex tachycardia when appropriate'],
    contra: ['Severe bradycardia', 'Decompensated heart failure', 'High-grade AV block'],
    routes: ['IV'],
    adult: '2.5–5 mg IV slow q5min (max 15 mg) per rate-control protocol',
    pediatric: 'Per medical direction',
  },
  {
    id: 'MED_MIDAZOLAM',
    name: 'Midazolam',
    minLevel: 'PARAMEDIC',
    ind: ['Seizures', 'Agitated patient', 'RSI adjunct'],
    contra: ['Severe respiratory depression'],
    routes: ['IV', 'IO', 'IM', 'IN'],
    adult: 'Seizure: 0.2 mg/kg IM (max 10 mg) or 0.1 mg/kg IV (max 4 mg) per guideline',
    pediatric: '0.2 mg/kg IM max 10; IV 0.1 mg/kg max 4 mg',
  },
  {
    id: 'MED_MORPHINE',
    name: 'Morphine sulfate',
    minLevel: 'PARAMEDIC',
    ind: ['ACS pain', 'Severe pain'],
    contra: ['Severe respiratory depression', 'Unstable ventilation'],
    routes: ['IV', 'IM'],
    adult: '2–4 mg slow IV titrate per pain/ACS protocol',
    pediatric: '0.05–0.1 mg/kg IV per protocol',
  },
  {
    id: 'MED_NALOXONE',
    name: 'Naloxone',
    minLevel: 'EMT',
    ind: ['Suspected opioid toxicity'],
    contra: ['Hypersensitivity'],
    routes: ['IV', 'IM', 'IN'],
    adult: 'IN/IM/IV 0.4–2 mg titrate to breathing (device-specific: 4 mg IN spray common)',
    pediatric: '0.04–0.1 mg/kg IV/IM/IN; escalate per guideline',
  },
  {
    id: 'MED_NIFEDIPINE',
    name: 'Nifedipine',
    minLevel: 'PARAMEDIC',
    ind: ['High-altitude pulmonary edema'],
    contra: ['Cardiogenic shock', 'Hypersensitivity'],
    routes: ['PO'],
    adult: '30 mg XR PO per altitude protocol (immediate-release not for hypertensive emergency)',
    pediatric: 'Per medical direction',
  },
  {
    id: 'MED_NITROUS_OXIDE',
    name: 'Nitrous oxide',
    minLevel: 'PARAMEDIC',
    ind: ['Self-administered analgesia where authorized'],
    contra: ['Pneumothorax', 'Bowel obstruction', 'Impaired ventilation'],
    routes: ['IN'],
    adult: '50% N2O with O2 patient-controlled per pain protocol',
    pediatric: 'Per policy',
  },
  {
    id: 'MED_NITROGLYCERIN',
    name: 'Nitroglycerin',
    minLevel: 'AEMT',
    ind: ['Chest pain / ACS', 'Acute pulmonary edema preload reduction'],
    contra: ['SBP <90 or ≥30 below baseline', 'Recent PDE-5 inhibitor', 'RV infarct (relative)', 'Bradycardia <50'],
    routes: ['SL', 'IV'],
    adult: '0.4 mg SL q3–5min if SBP >100; infusion per pulmonary edema protocol',
    pediatric: 'Rare—per medical direction',
  },
  {
    id: 'MED_NOREPINEPHRINE',
    name: 'Norepinephrine',
    minLevel: 'PARAMEDIC',
    ind: ['Refractory hypotension / shock'],
    contra: ['Hypovolemia uncorrected'],
    routes: ['IV'],
    adult: '0.02–0.4 mcg/kg/min IV titrate to MAP per shock protocol',
    pediatric: '0.05–0.3 mcg/kg/min per shock protocol',
  },
  {
    id: 'MED_OLANZAPINE',
    name: 'Olanzapine',
    minLevel: 'PARAMEDIC',
    ind: ['Acute agitation / psychosis'],
    contra: ['Hypersensitivity'],
    routes: ['IV', 'IM'],
    adult: '5–10 mg IM per behavioral protocol (observe post-dose)',
    pediatric: 'Per medical direction',
  },
  {
    id: 'MED_ONDANSETRON',
    name: 'Ondansetron',
    minLevel: 'AEMT',
    ind: ['Nausea and vomiting'],
    contra: ['Apomorphine co-administration', 'Long QT (relative)'],
    routes: ['IV', 'IM', 'PO'],
    adult: '4–8 mg IV/IM/ODT',
    pediatric: '0.15 mg/kg IV (max 8 mg)',
  },
  {
    id: 'MED_OXYMETAZOLINE',
    name: 'Oxymetazoline',
    minLevel: 'EMT',
    ind: ['Epistaxis with facial trauma'],
    contra: ['Hypersensitivity'],
    routes: ['IN'],
    adult: 'Topical intranasal per epistaxis protocol',
    pediatric: 'Dose per age/product label',
  },
  {
    id: 'MED_POTASSIUM_IODIDE',
    name: 'Potassium iodide',
    minLevel: 'EMT',
    ind: ['Radioiodine exposure prophylaxis'],
    contra: ['Iodine sensitivity contexts per protocol', 'Hyperthyroidism'],
    routes: ['PO'],
    adult: '130 mg PO daily during radiation emergency per public health dosing',
    pediatric: 'Age-based public health dosing (65 mg tablets crush)',
  },
  {
    id: 'MED_PREDNISONE',
    name: 'Prednisone',
    minLevel: 'PARAMEDIC',
    ind: ['Severe asthma / COPD', 'Allergic reaction when steroid indicated'],
    contra: ['Untreated serious infection', 'Hypersensitivity'],
    routes: ['PO'],
    adult: '40–60 mg PO per respiratory protocol',
    pediatric: '1–2 mg/kg PO (max 60 mg)',
  },
  {
    id: 'MED_PREDNISOLONE',
    name: 'Prednisolone',
    minLevel: 'PARAMEDIC',
    ind: ['Pediatric asthma / croup oral steroid'],
    contra: ['Same as prednisone'],
    routes: ['PO'],
    adult: 'Liquid equivalent per prednisone dose',
    pediatric: '1–2 mg/kg PO per guideline',
  },
  {
    id: 'MED_PRALIDOXIME',
    name: 'Pralidoxime chloride (2-PAM)',
    minLevel: 'PARAMEDIC',
    ind: ['Organophosphate / nerve agent exposure'],
    contra: ['Hypersensitivity'],
    routes: ['IV', 'IM'],
    adult: '1–2 g IV per tox protocol (autoinjector kit dosing)',
    pediatric: '20–40 mg/kg IV per tox protocol',
  },
  {
    id: 'MED_PROCAINAMIDE',
    name: 'Procainamide',
    minLevel: 'PARAMEDIC',
    ind: ['Stable wide-complex tachycardia (alternative agent)'],
    contra: ['Torsades', 'High-grade AV block', 'SLE (relative)'],
    routes: ['IV'],
    adult: '20–50 mg/min until arrhythmia suppressed or max 17 mg/kg—follow local infusion policy',
    pediatric: '15 mg/kg load over 30–60 min per protocol',
  },
  {
    id: 'MED_PROCHLORPERAZINE',
    name: 'Prochlorperazine',
    minLevel: 'PARAMEDIC',
    ind: ['Nausea / vomiting'],
    contra: ['Pediatric <2 years or <9 kg', 'Coma', 'Phenothiazine allergy'],
    routes: ['IV', 'IM'],
    adult: '5–10 mg IV/IM',
    pediatric: '0.15 mg/kg IM/IV per protocol',
  },
  {
    id: 'MED_SILDENAFIL',
    name: 'Sildenafil',
    minLevel: 'PARAMEDIC',
    ind: ['HAPE adjunct to descent when prescribed'],
    contra: ['Concomitant nitrates'],
    routes: ['PO'],
    adult: 'Per altitude medicine protocol only',
    pediatric: 'Not routine',
  },
  {
    id: 'MED_SODIUM_BICARBONATE',
    name: 'Sodium bicarbonate',
    minLevel: 'PARAMEDIC',
    ind: ['Hyperkalemia with arrest', 'Tricyclic overdose wide-complex', 'Severe metabolic acidosis per protocol'],
    contra: ['Severe alkalosis', 'Hypocalcemia (relative)'],
    routes: ['IV', 'IO'],
    adult: '1 mEq/kg IV bolus for TCA OD or hyperkalemia per arrest/tox protocol',
    pediatric: '1 mEq/kg IV per protocol',
  },
  {
    id: 'MED_SODIUM_NITRITE',
    name: 'Sodium nitrite',
    minLevel: 'PARAMEDIC',
    ind: ['Cyanide toxicity kit'],
    contra: ['Smoke inhalation with CO poisoning'],
    routes: ['IV'],
    adult: '300 mg IV over 5+ minutes per Nithiodote kit (follow protocol)',
    pediatric: 'Weight-based kit dosing',
  },
  {
    id: 'MED_SODIUM_THIOSULFATE',
    name: 'Sodium thiosulfate',
    minLevel: 'PARAMEDIC',
    ind: ['Cyanide toxicity (kit adjunct)'],
    contra: ['Hypersensitivity'],
    routes: ['IV'],
    adult: '12.5 g IV per kit following sodium nitrite',
    pediatric: '412.5 mg/kg IV (max 12.5 g)',
  },
  {
    id: 'MED_SORBITOL',
    name: 'Sorbitol',
    minLevel: 'PARAMEDIC',
    ind: ['Historically with charcoal—not recommended co-administration per NASEMSO note'],
    contra: ['Undifferentiated abdominal pain'],
    routes: ['PO'],
    adult: 'Not routine—per poisoning specialist only',
    pediatric: 'Avoid routine',
  },
  {
    id: 'MED_TADALAFIL',
    name: 'Tadalafil',
    minLevel: 'PARAMEDIC',
    ind: ['HAPE adjunct when prescribed'],
    contra: ['Concomitant nitrates'],
    routes: ['PO'],
    adult: 'Per altitude medicine / MD order',
    pediatric: 'Not routine',
  },
  {
    id: 'MED_ZIPRASIDONE',
    name: 'Ziprasidone',
    minLevel: 'PARAMEDIC',
    ind: ['Acute agitation'],
    contra: ['QT prolongation', 'Recent MI', 'Decompensated CHF'],
    routes: ['IM'],
    adult: '10–20 mg IM per behavioral protocol',
    pediatric: 'Per medical direction',
  },
];

export const PROCEDURES: ProcRow[] = [
  {
    id: 'PROC_12_LEAD_EKG',
    name: '12-lead ECG acquisition',
    category: 'Cardiac',
    minLevel: 'AEMT',
    ind: ['Chest pain', 'Suspected ACS', 'Syncope unexplained', 'Wide-complex tachycardia evaluation'],
    contra: ['None when clinically indicated'],
    equipment: ['ECG machine', 'Electrodes', 'Razor/skin prep'],
    parameters: 'Obtain within 10 minutes of contact for ACS suspicion',
    success: 'Diagnostic-quality tracing transmitted or hand-delivered',
  },
  {
    id: 'PROC_AED_USE',
    name: 'AED application and shock delivery',
    category: 'Cardiac',
    minLevel: 'EMT',
    ind: ['Cardiac arrest', 'Unwitnessed collapse with no pulse'],
    contra: ['Wet chest—dry before pads'],
    equipment: ['AED', 'Defibrillator pads'],
    parameters:
      'Follow device audio prompts; shock promptly when indicated; minimize pre- and peri-shock pause in compressions; resume CPR immediately',
    success: 'VF/VT terminated or device advises no shock; CPR resumed immediately',
  },
  {
    id: 'PROC_BAG_VALVE_MASK',
    name: 'Bag-valve-mask ventilation',
    category: 'Airway',
    minLevel: 'EMT',
    ind: ['Respiratory failure', 'Apnea', 'Preoxygenation prior to airway placement'],
    contra: ['None when alternative ventilation required'],
    equipment: ['BVM', 'Oxygen supply', 'OPA/NPA appropriate size'],
    parameters:
      'Adults (ACLS): ~**10 breaths/min** (1 breath q **6 s**) with **advanced airway** during CPR; **30:2** without. **Pediatrics (PALS):** with advanced airway use **continuous compressions** and **~1 breath every 2–3 s**; **30:2** or **15:2** without advanced airway per agency BLS. **Avoid excessive ventilation.**',
    success: 'Visible chest rise; SpO2 improves or CO2 trace when monitored',
  },
  {
    id: 'PROC_BIPAP',
    name: 'Non-invasive positive pressure ventilation (BiPAP)',
    category: 'Airway',
    minLevel: 'PARAMEDIC',
    ind: ['Respiratory failure with spontaneous ventilation', 'Pulmonary edema with distress'],
    contra: ['Apnea', 'Unable to protect airway', 'Severe facial trauma (relative)'],
    equipment: ['BiPAP device', 'Mask', 'Capnography if available'],
    parameters: 'IPAP/EPAP per protocol; continuous SpO2 monitoring',
    success: 'Reduced work of breathing; improved SpO2 and mentation',
  },
  {
    id: 'PROC_CAPNOGRAPHY',
    name: 'Continuous waveform capnography',
    category: 'Airway',
    minLevel: 'AEMT',
    ind: ['Procedural sedation', 'Intubated patient transport', 'CPR quality assessment'],
    contra: ['None'],
    equipment: ['EtCO2 sensor', 'Monitor'],
    parameters: 'Use EtCO2 numeric and waveform for tube confirmation and ROSC detection',
    success: 'Appropriate waveform for clinical context; abrupt change investigated',
  },
  {
    id: 'PROC_CARDIAC_MONITORING',
    name: 'Rhythm interpretation and cardiac monitoring',
    category: 'Cardiac',
    minLevel: 'AEMT',
    ind: ['Chest pain', 'Dysrhythmia symptoms', 'Post-arrest care', 'Wide-complex tachycardia'],
    contra: ['None'],
    equipment: ['Monitor', 'Defibrillation pads'],
    parameters: 'Lead II / 12-lead per presentation',
    success: 'Rhythm classified; therapy matched to guideline',
  },
  {
    id: 'PROC_CHEST_SEAL',
    name: 'Occlusive chest seal',
    category: 'Trauma',
    minLevel: 'EMT',
    ind: ['Open chest wound', 'Suspected tension pneumothorax with vented seal protocol'],
    contra: ['None when indicated for penetrating trauma'],
    equipment: ['Commercial chest seal', 'Occlusive dressing'],
    parameters: 'Three-sided or vented per protocol',
    success: 'Seal adheres; ventilatory dynamics monitored',
  },
  {
    id: 'PROC_CPAP',
    name: 'Continuous positive airway pressure (CPAP)',
    category: 'Airway',
    minLevel: 'AEMT',
    ind: ['Pulmonary edema', 'Severe respiratory distress with spontaneous breathing'],
    contra: ['Respiratory arrest', 'Severe hypotension', 'Vomiting inability to clear airway'],
    equipment: ['CPAP mask', 'PEEP valve', 'O2 high flow capability'],
    parameters: 'Start 5–10 cm H2O typical; titrate per SpO2 and distress',
    success: 'Improved SpO2 and reduced RR/work of breathing',
  },
  {
    id: 'PROC_DEFIBRILLATION',
    name: 'Unsynchronized defibrillation',
    category: 'Cardiac',
    minLevel: 'EMT',
    ind: ['VF', 'Pulseless VT'],
    contra: ['None in shockable arrest'],
    equipment: ['Defibrillator', 'Pads'],
    parameters:
      'Adult: biphasic per manufacturer (often initial 120–200 J; if unknown use maximum available); monophasic 360 J; repeat equivalent or higher as appropriate; pediatric manual energy **2 J/kg** initial then **4 J/kg** subsequent (pediatric attenuator or joules/kg per device); minimize compression pause surrounding shock',
    success: 'Rhythm no longer VF after shock; ROSC or organized rhythm',
  },
  {
    id: 'PROC_HEMORRHAGE_CONTROL',
    name: 'Direct pressure and wound packing',
    category: 'Trauma',
    minLevel: 'EMT',
    ind: ['External hemorrhage'],
    contra: ['None'],
    equipment: ['Hemostatic gauze', 'Standard gauze', 'Pressure dressing'],
    parameters: 'Pack deep tracks; maintain pressure until definitive care',
    success: 'Bleeding controlled or significantly reduced',
  },
  {
    id: 'PROC_IO_ACCESS',
    name: 'Intraosseous access',
    category: 'Medical',
    minLevel: 'AEMT',
    ind: ['Cardiac arrest', 'Shock when IV unsuccessful', 'Severe burns edema'],
    contra: ['Fracture at site', 'Previous IO same bone (relative)', 'Infection over site'],
    equipment: ['IO driver / needle', 'IV tubing', 'Lactated ringers'],
    parameters: 'Proximal tibia or humerus adult; distal femur/tibia pediatric—per device',
    success: 'Needle upright; flush easily; meds delivered',
  },
  {
    id: 'PROC_IV_ACCESS',
    name: 'Peripheral intravenous access',
    category: 'Medical',
    minLevel: 'AEMT',
    ind: ['Fluid/medication delivery', 'Contrast allergy prep', 'Unstable patient'],
    contra: ['Affected limb vascular injury', 'Dialysis fistula arm'],
    equipment: ['Angiocath set', 'NS flush', 'Tourniquet'],
    parameters: 'Large-bore preferred in shock',
    success: 'Patent IV; no signs of extravasation',
  },
  {
    id: 'PROC_MANUAL_DEFIBRILLATION',
    name: 'Manual defibrillator operation',
    category: 'Cardiac',
    minLevel: 'PARAMEDIC',
    ind: ['VF/pulseless VT', 'Unstable tachycardia when synchronized mode unavailable initially'],
    contra: ['Oxygen-rich env—brief pause ventilation during shock'],
    equipment: ['Manual defibrillator', 'Paddles or pads'],
    parameters:
      'Adult: manufacturer-recommended biphasic energy (if unknown, maximum available); monophasic 360 J; pediatric arrest commonly **2 J/kg** then **4 J/kg** manual dosing per PALS; minimize compression pause',
    success: 'Effective shock delivery with minimal compression pause',
  },
  {
    id: 'PROC_MECHANICAL_VENTILATION',
    name: 'Mechanical ventilator transport',
    category: 'Airway',
    minLevel: 'PARAMEDIC',
    ind: ['Interfacility transport of intubated ventilated patient'],
    contra: ['None when ventilator available and trained'],
    equipment: ['Transport ventilator', 'Capnography', 'Spare circuits'],
    parameters: 'Match rate/tidal volume/PEEP to sending facility orders',
    success: 'Stable EtCO2 and SpO2 throughout transport',
  },
  {
    id: 'PROC_NEEDLE_DECOMPRESSION',
    name: 'Needle decompression tension pneumothorax',
    category: 'Trauma',
    minLevel: 'PARAMEDIC',
    ind: ['Suspected tension pneumothorax with hemodynamic compromise'],
    contra: ['None in life-threatening emergency'],
    equipment: ['14–16G angiocath', 'Antiseptic', 'Occlusive dressing after (per protocol)'],
    parameters: '2nd ICS MCL or 4th–5th ICS anterior axillary per protocol',
    success: 'Improved perfusion/BSI after decompression; reassess frequently',
  },
  {
    id: 'PROC_OBSTETRIC_EMERGENCY_CARE',
    name: 'Emergency obstetric care (childbirth, cord, newborn)',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Imminent delivery', 'OB hemorrhage support'],
    contra: ['None when delivery imminent'],
    equipment: ['OB kit', 'Bulb suction', 'Warm blankets', 'Clamps'],
    parameters: 'Support controlled delivery; warm-dry-stimulate newborn',
    success: 'Vital newborn; controlled cord; mother stabilized for transport',
  },
  {
    id: 'PROC_GLUCOMETRY',
    name: 'Point-of-care blood glucose (glucometry)',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Altered mental status', 'Seizure', 'Hypoglycemia symptoms'],
    contra: ['None'],
    equipment: ['Glucometer', 'Test strips', 'Lancet'],
    parameters: 'Confirm machine calibration; repeat if discordant with clinical picture',
    success: 'Accurate glucose documented and treated per guideline',
  },
  {
    id: 'PROC_RESTRAINTS',
    name: 'Physical / chemical restraint protocol',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Imminent danger to self or others when de-escalation fails'],
    contra: ['None when safety imperative—monitor airway and circulation continuously'],
    equipment: ['Soft restraints', 'Law enforcement assistance as policy', 'Monitoring'],
    parameters: 'Least restrictive effective; never prone',
    success: 'Patient and crew safe; continuous assessment documented',
  },
  {
    id: 'PROC_RSI',
    name: 'Rapid sequence intubation',
    category: 'Airway',
    minLevel: 'PARAMEDIC',
    ind: ['GCS <= 8', 'Unable to protect airway', 'Severe hypoxia refractory to NIV', 'Traumatic airway compromise'],
    contra: ['Cannot oxygenate—consider surgical airway'],
    equipment: ['Suction', 'Video laryngoscope', 'ET tubes', 'BVM', 'Push drugs', 'Capnography'],
    parameters: 'Preoxygenate; induction + paralytic per protocol',
    success: 'EtCO2 waveform with ventilation; SpO2 maintained',
  },
  {
    id: 'PROC_SPINAL_MOTION_RESTRICTION',
    name: 'Spinal motion restriction',
    category: 'Trauma',
    minLevel: 'EMT',
    ind: ['Mechanism with suspected spine injury', 'Neurogenic symptoms'],
    contra: ['Clear spine criteria met (per local guideline)'],
    equipment: ['C-collar', 'Backboard or scoop optional per policy', 'Head blocks'],
    parameters: 'Manual inline stabilization until collar sized',
    success: 'Pain/numbness reassessed; immobilization tolerable',
  },
  {
    id: 'PROC_SUPRAGLOTTIC_AIRWAY',
    name: 'Supraglottic airway placement',
    category: 'Airway',
    minLevel: 'AEMT',
    ind: ['Ventilation difficulty with BVM', 'Cardiac arrest airway adjunct', 'Bridge to intubation'],
    contra: ['Complete upper airway obstruction', 'Severe aspiration risk (relative)'],
    equipment: ['SGA device', 'Lubricant', 'BVM'],
    parameters: 'Size per anthropometry; second verification with capnography',
    success: 'Easy BVM ventilation; audible leak controlled',
  },
  {
    id: 'PROC_SURGICAL_CRIC',
    name: 'Surgical cricothyrotomy',
    category: 'Airway',
    minLevel: 'PARAMEDIC',
    ind: ['Cannot intubate cannot oxygenate', 'Massive facial trauma'],
    contra: ['Pediatric larynx (needle technique preferred)'],
    equipment: ['Scalpel 10–11', 'Tracheal hook', '6-0 cuffed tube or commercial kit'],
    parameters: 'Identify cricothyroid membrane; confirm with EtCO2',
    success: 'Ventilation possible; hemorrhage controlled',
  },
  {
    id: 'PROC_SYNC_CARDIOVERSION',
    name: 'Synchronized cardioversion',
    category: 'Cardiac',
    minLevel: 'PARAMEDIC',
    ind: ['Unstable tachydysrhythmia with pulse', 'SBP <90 with altered mental status from arrhythmia'],
    contra: ['Digitalis toxicity tachyarrhythmia (relative—lower energy)'],
    equipment: ['Manual cardioverter', 'Sedation agents', 'Pads'],
    parameters:
      'Adult: **synchronized mode**; use device-recommended energy—or **maximum biphasic output if unknown**—then escalate if refractory; sedate when feasible; **PALS:** unstable tachyarrhythmia with pulse often **0.5–1 J/kg** initial synchronized cardioversion then escalate per PALS',
    success: 'Restoration of perfusing rhythm or improved perfusion',
  },
  {
    id: 'PROC_TOURNIQUET',
    name: 'Arterial tourniquet application',
    category: 'Trauma',
    minLevel: 'EMT',
    ind: ['Life-threatening extremity hemorrhage'],
    contra: ['None in exsanguinating extremity hemorrhage'],
    equipment: ['Commercial tourniquet', 'Time marker'],
    parameters: 'High and tight; note time; only loosen in hospital',
    success: 'Bleeding controlled; distal pulse absent expected',
  },
  {
    id: 'PROC_INTUBATION',
    name: 'Orotracheal intubation',
    category: 'Airway',
    minLevel: 'PARAMEDIC',
    ind: ['Airway protection', 'Refractory hypoxemia', 'Expected clinical course'],
    contra: ['Anatomy predicts impossible laryngoscopy without backup'],
    equipment: ['Laryngoscope', 'ETT 6.0–8.5 typical adult', 'Stylet', 'Suction', 'BVM'],
    parameters: 'ETT depth ~21–23 cm at teeth adult; confirm bilateral breath sounds + EtCO2',
    success: 'Continuous EtCO2 waveform; SpO2 acceptable',
  },
  {
    id: 'PROC_TRANSCUTANEOUS_PACING',
    name: 'Transcutaneous pacing',
    category: 'Cardiac',
    minLevel: 'PARAMEDIC',
    ind: ['Hemodynamically unstable bradycardia unresponsive to atropine'],
    contra: ['Asystole (ineffective)—treat underlying cause'],
    equipment: ['Defibrillator with pacing mode', 'Pads'],
    parameters: 'Start ~80 mA typical adult; titrate from lower output in pediatrics per capture; increase until capture; mA above capture for margin',
    success: 'Electrical and mechanical capture; improved perfusion',
  },
  {
    id: 'PROC_NEEDLE_CRIC',
    name: 'Needle cricothyrotomy / percutaneous airway',
    category: 'Airway',
    minLevel: 'PARAMEDIC',
    ind: ['Pediatric upper airway obstruction', 'Cannot intubate cannot oxygenate (pediatric)'],
    contra: ['None in imminent airway loss'],
    equipment: ['Cricothyrotomy catheter kit', 'Jet vent device if available'],
    parameters: 'Verify landmark; saline coupling if jet ventilation',
    success: 'Oxygenation improved; plan for definitive airway',
  },
  {
    id: 'PROC_GUIDELINE_ABDOMINAL_PAIN',
    name: 'Abdominal pain assessment and supportive care',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Abdominal pain', 'Suspected intra-abdominal emergency'],
    contra: ['None for assessment—avoid blind palpation if AAA suspected'],
    equipment: ['Monitor', 'IV supplies', 'Antiemetics per protocol'],
    parameters: 'Trend vitals; NPO; surgical abdomen considerations',
    success: 'Pain trended; timely transport to appropriate facility',
  },
  {
    id: 'PROC_GUIDELINE_ACS_CHEST_PAIN',
    name: 'Chest pain / ACS / STEMI care bundle',
    category: 'Cardiac',
    minLevel: 'EMT',
    ind: ['Chest pain suspected ACS', 'STEMI criteria on 12-lead'],
    contra: ['Triage delays—minimize scene time'],
    equipment: ['12-lead ECG', 'Aspirin', 'Nitroglycerin if appropriate', 'Monitor'],
    parameters: 'Aspirin 162–325 mg chewable; SL NTG if SBP >100; STEMI alert',
    success: 'Aspirin documented; ECG <10 min; cath lab activation if indicated',
  },
  {
    id: 'PROC_GUIDELINE_AGITATED_PATIENT',
    name: 'Agitated / violent patient—de-escalation and sedation pathway',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Dangerous agitation', 'Psychosis with violence risk'],
    contra: ['Sedation without monitoring capability'],
    equipment: ['Restraints', 'Sedation agents per scope', 'Capnography when sedated'],
    parameters: 'Verbal de-escalation first; avoid prone restraint',
    success: 'Patient calmer; crew and patient safe',
  },
  {
    id: 'PROC_GUIDELINE_AIRWAY_MANAGEMENT',
    name: 'Universal airway management algorithm',
    category: 'Airway',
    minLevel: 'EMT',
    ind: ['Airway compromise', 'Ventilation failure'],
    contra: ['Apnea without immediate BVM—act'],
    equipment: ['Suction', 'OPA/NPA', 'BVM', 'Advanced airway as level permits'],
    parameters: 'Head position; suction; **continuous waveform capnography when an advanced airway is placed**; escalate per difficulty',
    success: 'Adequate oxygenation and ventilation',
  },
  {
    id: 'PROC_GUIDELINE_ALTITUDE_ILLNESS',
    name: 'Altitude illness (AMS/HACE/HAPE) care',
    category: 'Medical',
    minLevel: 'PARAMEDIC',
    ind: ['High-altitude headache with ataxia or AMS', 'HAPE hypoxia at altitude'],
    contra: ['Delayed descent when HACE/HAPE suspected'],
    equipment: ['Pulse oximeter', 'Portable O2', 'Dexamethasone / nifedipine per protocol'],
    parameters: 'Descent is definitive; oxygen; avoid sedatives depressing respiration',
    success: 'Improved SpO2 and mental status during evacuation',
  },
  {
    id: 'PROC_GUIDELINE_ANAPHYLAXIS',
    name: 'Anaphylaxis and allergic reaction management',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Multisystem allergic reaction', 'Hypotension with urticaria', 'Respiratory compromise from allergy'],
    contra: ['None for epinephrine in life-threatening anaphylaxis'],
    equipment: ['Epinephrine IM', 'Albuterol neb', 'IV/IO supplies', 'Diphenhydramine'],
    parameters: 'Epinephrine IM early; IV fluids 20 mL/kg for hypoperfusion',
    success: 'Blood pressure and airway improved after first-line therapy',
  },
  {
    id: 'PROC_GUIDELINE_BRADYCARDIA',
    name: 'Symptomatic bradycardia management',
    category: 'Cardiac',
    minLevel: 'PARAMEDIC',
    ind: ['Hypotensive bradycardia', 'AMS with slow rate', 'Chest pain with bradycardia'],
    contra: ['None when unstable and pacing indicated'],
    equipment: ['Atropine', 'Pacing pads', 'Dopamine/epinephrine infusion'],
    parameters:
      'Adults (ACLS): atropine 1 mg IV; repeat every 3–5 min to maximum 3 mg total; transcutaneous pacing if unstable or drugs inadequate; epinephrine or dopamine infusion if pacing delayed or ineffective. **PALS:** oxygen/ventilation first for symptomatic bradycardia; atropine **0.02 mg/kg IV/IO** (min 0.1 mg, max 0.5 mg) **may repeat once** in ≈5 min; TCP if unstable with poor perfusion; infusion if pacing delayed. Treat underlying causes.',
    success: 'HR and perfusion improved',
  },
  {
    id: 'PROC_GUIDELINE_BURNS',
    name: 'Burns—cooling, fluid estimate, transport',
    category: 'Trauma',
    minLevel: 'EMT',
    ind: ['Thermal burn', 'Airway risk inhalational injury'],
    contra: ['Hypothermia from prolonged cooling'],
    equipment: ['Sterile dressings', 'Lactated ringers', 'Burn charts appendix reference'],
    parameters: 'Stop burning process; estimate TBSA; fluid bolus per pediatric policy',
    success: 'Pain controlled; warm patient after focal cooling',
  },
  {
    id: 'PROC_GUIDELINE_CARDIAC_ARREST',
    name: 'Cardiac arrest (VF/VT/asystole/PEA) resuscitation',
    category: 'Cardiac',
    minLevel: 'EMT',
    ind: ['Pulseless apneic patient'],
    contra: ['DNR/termination criteria per policy'],
    equipment: ['Defibrillator/AED', 'BVM', 'CPR adjuncts', 'Epinephrine', 'Advanced airway'],
    parameters:
      '**Adults (ACLS):** High-quality CPR: depth ≥2 in (≈5 cm), rate 100–120/min, full recoil, minimize pauses, chest compression fraction >80% when measured, no excessive ventilation; 30:2 without advanced airway; with advanced airway continuous compressions with 1 breath every 6 s (~10/min); **waveform capnography** with advanced airway. Shock VF/pVT promptly; **biphasic defibrillation per manufacturer** (often **120–200 J** initially; **if unknown use maximum available**); **monophasic 360 J**; **epinephrine 1 mg IV/IO as soon as IV/IO access is established**, then **q3–5 min**; **amiodarone 300 mg IV/IO** then **150 mg IV/IO** (or **lidocaine 1–1.5 mg/kg** then **0.5–0.75 mg/kg**) for refractory VF/pVT. Do not defibrillate asystole/PEA. **PALS:** epinephrine **0.01 mg/kg IV/IO q3–5 min**; VF/pVT **2 J/kg** then **4 J/kg**; compress ≥1/3 AP depth at 100–120/min; **15:2** (two rescuers) or **30:2** (single) without advanced airway; with advanced airway **continuous compressions + ~1 breath every 2–3 s** (~20–30/min)—**avoid hyperventilation**; refractory VF/pVT **amiodarone 5 mg/kg** (max 300 mg).',
    success: 'ROSC or organized termination per guideline',
  },
  {
    id: 'PROC_GUIDELINE_CRUSH_INJURY',
    name: 'Crush injury / rhabdomyolysis support',
    category: 'Trauma',
    minLevel: 'AEMT',
    ind: ['Prolonged limb entrapment', 'Suspected crush syndrome'],
    contra: ['Tourniquet unless life-threatening bleed—reperfusion planning'],
    equipment: ['Large-bore IV', 'Normal saline', 'Monitor'],
    parameters: 'Aggressive isotonic fluid prior to release when safe',
    success: 'Vitals stable through extrication and transport',
  },
  {
    id: 'PROC_GUIDELINE_CYANIDE',
    name: 'Cyanide exposure antidote pathway',
    category: 'Medical',
    minLevel: 'PARAMEDIC',
    ind: ['Smoke inhalation with suspicion of cyanide', 'Industrial cyanide exposure'],
    contra: ['Amyl nitrite / sodium nitrite relatively contraindicated if isolated CO—use hydroxocobalamin per tox'],
    equipment: ['Hydroxocobalamin kit', 'Oxygen', 'Second line nitrites per protocol'],
    parameters: 'IV access; hydroxocobalamin 5 g adult; draw labs before if feasible',
    success: 'Hemodynamics and mentation trend better with antidote',
  },
  {
    id: 'PROC_GUIDELINE_DROWNING',
    name: 'Drowning and submersion resuscitation',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Submersion with respiratory arrest', 'Hypoxia after rescue'],
    contra: ['None—prioritize oxygenation'],
    equipment: ['Suction', 'BVM', 'Warm blankets'],
    parameters:
      'Spinal precautions if mechanism; standard BLS/CPR when pulseless—prioritize oxygenation/ventilation after submersion; oxygen; targeted temperature if ROSC',
    success: 'Spontaneous breathing or ventilatory support adequate',
  },
  {
    id: 'PROC_GUIDELINE_ELECTRICAL_INJURY',
    name: 'Electrical and lightning injury care',
    category: 'Trauma',
    minLevel: 'EMT',
    ind: ['Cardiac monitoring after electrical contact', 'Lightning strike', 'Entry/exit wounds'],
    contra: ['Assume occult dysrhythmia—monitor'],
    equipment: ['Monitor/defibrillator', 'Burn care supplies'],
    parameters: 'ECG even if asymptomatic; prolonged monitoring per exposure voltage',
    success: 'Stable rhythm; burns dressed; secondary survey complete',
  },
  {
    id: 'PROC_GUIDELINE_END_OF_LIFE',
    name: 'End-of-life / hospice comfort care transport',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Comfort-focused care per POLST', 'DNR with symptom crisis'],
    contra: ['Resuscitation when POLST indicates comfort measures only'],
    equipment: ['Symptom meds per order', 'Oxygen comfort'],
    parameters: 'Align interventions with goals-of-care documentation',
    success: 'Patient comfort honored; family expectations met',
  },
  {
    id: 'PROC_GUIDELINE_GENERAL_TRAUMA',
    name: 'General trauma—primary survey, hemorrhage, transport',
    category: 'Trauma',
    minLevel: 'EMT',
    ind: ['Multi-system trauma', 'Mechanism concerning for severe injury'],
    contra: ['Scene delays—load and go when indicated'],
    equipment: ['C-spine kit', 'Tourniquet', 'Hemorrhage control', 'Pelvic binder'],
    parameters: 'ABCDE; 10 min scene goal when unstable',
    success: 'Life threats addressed; appropriate trauma center',
  },
  {
    id: 'PROC_GUIDELINE_HEAD_INJURY',
    name: 'Traumatic brain injury—ICP considerations',
    category: 'Trauma',
    minLevel: 'EMT',
    ind: ['GCS decline', 'Battle sign', 'Combativeness post head strike'],
    contra: ['Hypoxia and hypotension worsen secondary injury'],
    equipment: ['Capnography if intubated', 'Hyperosmolar therapy if protocol'],
    parameters: 'Elevate head 30° when spine cleared; avoid hypotension',
    success: 'GCS stable or improved; SpO2 >94%',
  },
  {
    id: 'PROC_GUIDELINE_HEAT_ILLNESS',
    name: 'Hyperthermia / heat stroke cooling',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Hot environment with AMS', 'Core temp elevation', 'Exertional collapse'],
    contra: ['Ice packs only without active cooling in heat stroke'],
    equipment: ['Ice sheets', 'Misting', 'Monitor'],
    parameters: 'Rapid cooling; IV fluids when indicated',
    success: 'Mental status improves with cooling',
  },
  {
    id: 'PROC_GUIDELINE_HYPERGLYCEMIA',
    name: 'Hyperglycemia with ketosis / dehydration',
    category: 'Medical',
    minLevel: 'AEMT',
    ind: ['DKA symptoms', 'Severe hyperglycemia with vomiting'],
    contra: ['Fluid cautiously in CHF—titrate'],
    equipment: ['IV NS', 'Monitor', 'Glucometer'],
    parameters: 'Fluid resuscitation per guideline; insulin in hospital',
    success: 'Hemodynamics support until ED insulin',
  },
  {
    id: 'PROC_GUIDELINE_HYPOGLYCEMIA',
    name: 'Hypoglycemia treatment pathway',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Blood glucose low', 'AMS with suspected hypoglycemia'],
    contra: ['Confirm glucose before large dextrose if uncertain'],
    equipment: ['D10 or D50', 'Glucagon IM', 'Glucometer'],
    parameters: 'D10 preferred; recheck glucose after treatment',
    success: 'GCS normalizes with normoglycemia',
  },
  {
    id: 'PROC_GUIDELINE_HYPOTHERMIA',
    name: 'Hypothermia rewarming and resuscitation',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Cold exposure', 'Core temp low', 'Trauma in cold'],
    contra: ['Rough movement in severe hypothermia—arrest rhythms'],
    equipment: ['Warm blankets', 'Warm IV fluids', 'Cardiac monitor'],
    parameters: 'Gentle handling; active rewarming for moderate/severe',
    success: 'Core temperature rises; perfusion improves',
  },
  {
    id: 'PROC_GUIDELINE_LVAD',
    name: 'Ventricular assist device patient support',
    category: 'Cardiac',
    minLevel: 'AEMT',
    ind: ['LVAD patient with pump thrombosis concern', 'Arrhythmia with MAP palpation'],
    contra: ['Chest compressions only if directed by device team protocol'],
    equipment: ['Doppler MAP', 'Monitor', 'Anticoagulation awareness'],
    parameters: 'Palpate for pulse; treat perfusion not numeric BP alone',
    success: 'Device flow restored or patient at VAD center',
  },
  {
    id: 'PROC_GUIDELINE_NAUSEA_VOMITING',
    name: 'Nausea and vomiting symptomatic care',
    category: 'Medical',
    minLevel: 'AEMT',
    ind: ['Debilitating nausea', 'Vomiting with dehydration risk'],
    contra: ['Obstructed bowel before prokinetics'],
    equipment: ['Antiemetics per scope', 'IV fluids'],
    parameters: 'Ondansetron / metoclopramide per protocol',
    success: 'Symptoms reduced; able to tolerate transport',
  },
  {
    id: 'PROC_GUIDELINE_NEONATAL_RESUSCITATION',
    name: 'Neonatal resuscitation basics',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Newborn apneic or bradycardic after delivery'],
    contra: ['Delayed drying/stimulation'],
    equipment: ['Warm radiant environment', 'Bulb suction', 'BVM neonatal'],
    parameters: 'Dry/warm/stimulate; suction if airway obstructed; **effective ventilation first**; CPAP if breathing effort poor—if HR remains <60 after adequate ventilation, **3:1** compressions:breaths per NRP-style neonatal CPR',
    success: 'HR >100 with effective ventilation',
  },
  {
    id: 'PROC_GUIDELINE_OPIOID_OVERDOSE',
    name: 'Opioid poisoning / overdose',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Respiratory depression with opioid toxidrome', 'Pinpoint pupils'],
    contra: ['Naloxone-induced pulmonary edema risk—titrate'],
    equipment: ['Naloxone IV/IM/IN', 'BVM'],
    parameters: 'Airway first; small repeat naloxone doses to spontaneous vent',
    success: 'Adequate respiratory effort without violent withdrawal if avoidable',
  },
  {
    id: 'PROC_GUIDELINE_PAIN_MANAGEMENT',
    name: 'Prehospital analgesia protocol',
    category: 'Medical',
    minLevel: 'PARAMEDIC',
    ind: ['Moderate–severe pain', 'Long transport'],
    contra: ['Hypotension before opioids—fluid first'],
    equipment: ['Fentanyl/morphine/ketorolac per formulary', 'Monitor'],
    parameters: 'Titrate to effect; re-assess q5min',
    success: 'Pain score decreases; vitals stable',
  },
  {
    id: 'PROC_GUIDELINE_POISONING_UNIVERSAL',
    name: 'Poisoning / overdose universal assessment',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Unknown toxidrome', 'Intentional overdose'],
    contra: ['Activated charcoal when contraindicated—see tox Pearl'],
    equipment: ['Charcoal if appropriate', 'Decon supplies', 'Monitor'],
    parameters: 'Protect airway; identify agent; contact poison center',
    success: 'Stable airway; packaging for transport',
  },
  {
    id: 'PROC_GUIDELINE_POST_ROSC',
    name: 'Post–return of spontaneous circulation care',
    category: 'Cardiac',
    minLevel: 'PARAMEDIC',
    ind: ['ROSC after cardiac arrest'],
    contra: ['Sustained hyperoxia—titrate to SpO2 90–98% (PaO2 ~60–105 mm Hg) when reliable'],
    equipment: ['Advanced airway', 'Pressors', '12-lead', 'Temperature control'],
    parameters:
      'Maintain high FiO2 until SpO2 (or PaO2) is reliably measured, then titrate FiO2 for SpO2 90–98% (PaO2 ~60–105 mm Hg); ventilate toward PCO2 35–45 mm Hg; MAP ≥65 mm Hg; 12-lead for STEMI/ischemia; if not following commands off sedation/NMB, deliberate temperature control goal 32–37.5 °C ASAP',
    success: 'BP and oxygenation supported en route to definitive care',
  },
  {
    id: 'PROC_GUIDELINE_RESPIRATORY_DISTRESS',
    name: 'Respiratory distress (bronchospasm / pulmonary edema) pathway',
    category: 'Airway',
    minLevel: 'EMT',
    ind: ['SpO2 <90% on high-flow O2', 'Tripod', 'Accessory muscle use'],
    contra: ['CPAP when vomiting/aspiration risk uncontrolled'],
    equipment: ['Albuterol/ipratropium', 'CPAP', 'Epinephrine IM if anaphylaxis mimic'],
    parameters: 'Position upright; neb; escalate to CPAP/NIV',
    success: 'RR decreases; SpO2 improves',
  },
  {
    id: 'PROC_GUIDELINE_SEIZURE',
    name: 'Seizure and status epilepticus',
    category: 'Medical',
    minLevel: 'PARAMEDIC',
    ind: ['Generalized seizure >5 minutes', 'Cluster seizures', 'Postictal prolonged'],
    contra: ['Nothing in mouth during seizure'],
    equipment: ['Midazolam IM/IN/IV', 'Lorazepam IV', 'Glucose check'],
    parameters: 'Midazolam 0.2 mg/kg IM max 10 mg per guideline',
    success: 'Seizure activity stops; airway protected',
  },
  {
    id: 'PROC_GUIDELINE_SHOCK',
    name: 'Shock—fluid and vasopressor strategy',
    category: 'Medical',
    minLevel: 'AEMT',
    ind: ['SBP <90', 'MAP <65', 'Delayed capillary refill with tachycardia'],
    contra: ['Fluid overload in flash pulmonary edema—vasopressors'],
    equipment: ['Two large-bore IVs', 'Warm crystalloid', 'Pressors'],
    parameters: '20 mL/kg boluses pediatric; 1–2 L adult crystalloid per guideline',
    success: 'MAP improved or signs of fluid responsiveness',
  },
  {
    id: 'PROC_GUIDELINE_SICKLE_CELL_CRISIS',
    name: 'Sickle cell pain crisis support',
    category: 'Medical',
    minLevel: 'PARAMEDIC',
    ind: ['Vaso-occlusive pain in known SCD', 'Fever with crisis'],
    contra: ['Assume infection if febrile—transport'],
    equipment: ['Oxygen', 'Analgesia', 'Warm fluids'],
    parameters: 'Rapid analgesia; avoid unnecessary hypoxia or cold',
    success: 'Pain trend improved; hemodynamics stable',
  },
  {
    id: 'PROC_GUIDELINE_STROKE_TIA',
    name: 'Suspected stroke / TIA triage',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Sudden neuro deficit', 'Last known well time critical'],
    contra: ['Hypoglycemia mimicking stroke—check glucose'],
    equipment: ['Stroke scale', 'Glucometer', 'BP management per policy'],
    parameters: 'Document LKW; avoid unnecessary BP lowering unless protocol exception',
    success: 'Notification to stroke center; transport without delay',
  },
  {
    id: 'PROC_GUIDELINE_SYNCOPE',
    name: 'Syncope / near-syncope evaluation',
    category: 'Cardiac',
    minLevel: 'EMT',
    ind: ['Transient LOC with recovery', 'Orthostatic symptoms'],
    contra: ['STEMI must be ruled out when atypical'],
    equipment: ['12-lead', 'Orthostatic vitals if safe'],
    parameters: 'Risk stratify; PE/AAA red flags',
    success: 'High-risk patients transported; education for low-risk',
  },
  {
    id: 'PROC_GUIDELINE_TACHYCARDIA',
    name: 'Tachycardia with pulse—stable vs unstable',
    category: 'Cardiac',
    minLevel: 'PARAMEDIC',
    ind: ['Wide-complex tachycardia', 'Narrow-complex SVT', 'Rapid AF'],
    contra: ['Unstable = cardioversion; avoid adenosine for irregular wide'],
    equipment: ['Adenosine', 'Cardioversion', 'Amiodarone/procainamide for stable wide'],
    parameters:
      'Unstable tachycardia with serious signs → immediate synchronized cardioversion (or unsynchronized if VF/pVT); use **device-recommended energy or maximum biphasic output if unknown**. Stable regular narrow-complex → vagal maneuvers then **adenosine 6 mg rapid IV push with NS flush**, then **12 mg with flush** if needed; stable wide-complex VT → IV antiarrhythmic per ACLS (procainamide/amiodarone); irregular wide → avoid adenosine; polymorphic VT often unstable—defibrillate per ACLS. **PALS:** unstable SVT/V-Tach with pulse often **0.5–1 J/kg** synchronized initially; stable narrow regular → **weight-based adenosine** per PALS.',
    success: 'Rate or rhythm controlled; perfusion restored',
  },
  {
    id: 'PROC_GUIDELINE_TRACHEOSTOMY',
    name: 'Tracheostomy / stoma emergency management',
    category: 'Airway',
    minLevel: 'EMT',
    ind: ['Trach patient with obstruction', 'Accidental decannulation'],
    contra: ['Blind deep suction past stoma'],
    equipment: ['Suction', 'Spare same-size trach', 'BVM stoma interface'],
    parameters: 'Patency first; oxygen through stoma',
    success: 'Ventilation patent; SpO2 acceptable',
  },
  {
    id: 'PROC_GUIDELINE_TRAUMA_ARREST',
    name: 'Traumatic cardiac arrest protocol',
    category: 'Trauma',
    minLevel: 'EMT',
    ind: ['Traumatic PEA', 'Tension pneumo suspected in trauma arrest'],
    contra: ['Medical arrest algorithms alone without addressing trauma reversible causes'],
    equipment: ['MTP activation if policy', 'Thoracotomy center transport', 'Blood products if available'],
    parameters: 'CPR with high-quality breathing/circulation support while addressing reversible causes; bilateral decompress if indicated; hypovolemia resuscitation',
    success: 'ROSC or transport for definitive surgical rescue',
  },
  {
    id: 'PROC_GUIDELINE_BLAST_INJURY',
    name: 'Blast injury assessment and early care',
    category: 'Trauma',
    minLevel: 'EMT',
    ind: ['Explosion mechanism', 'Multi-casualty blast', 'Eardrum injury pattern'],
    contra: ['Secondary device suspicion—scene safety'],
    equipment: ['Tourniquets', 'Ventilation supplies', 'Thermal burn care'],
    parameters: 'Primary blast: barotrauma; secondary: fragmentation; tertiary: blunt; quaternary: tox/burn',
    success: 'Rapid triage; life threats addressed',
  },
  {
    id: 'PROC_GUIDELINE_BRONCHIOLITIS',
    name: 'Pediatric bronchiolitis / viral wheeze support',
    category: 'Airway',
    minLevel: 'EMT',
    ind: ['Infant wheeze with URI symptoms', 'Increased work of breathing'],
    contra: ['Routine bronchodilator may be ineffective—trial per protocol'],
    equipment: ['High-flow O2', 'Neb if authorized', 'Suction'],
    parameters: 'Hydration; nasal suction; escalate to advanced care if apnea or SpO2 fails',
    success: 'Reduced retractions and improved SpO2',
  },
  {
    id: 'PROC_GUIDELINE_BRUE',
    name: 'Brief resolved unexplained event (BRUE) evaluation',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Infant transient cyanosis or apnea resolved', 'ALTE legacy concern'],
    contra: ['High-risk BRUE criteria require ED evaluation'],
    equipment: ['Monitor', 'Glucometer', 'Thermometer'],
    parameters: 'Risk stratify per newest guideline; observe during transport',
    success: 'Stable vitals en route; appropriate disposition messaging',
  },
  {
    id: 'PROC_GUIDELINE_CROUP',
    name: 'Pediatric croup / stridor management',
    category: 'Airway',
    minLevel: 'EMT',
    ind: ['Stridor at rest', 'Seal-like cough', 'Post-tussive stridor'],
    contra: ['Epiglottitis suspected—avoid agitation'],
    equipment: ['Neb racemic epinephrine if carried', 'Steroid IM/IV', 'Heliox if available'],
    parameters: 'Dexamethasone per protocol; epinephrine neb for moderate–severe',
    success: 'Stridor improves; child calm and SpO2 adequate',
  },
  {
    id: 'PROC_GUIDELINE_ECLAMPSIA',
    name: 'Eclampsia / severe preeclampsia seizure care',
    category: 'Medical',
    minLevel: 'PARAMEDIC',
    ind: ['Pregnancy with seizure', 'Severe HTN with headache/visual change'],
    contra: ['Repeat seizures—load magnesium per OB protocol'],
    equipment: ['Magnesium sulfate', 'Antihypertensives', 'OB pads'],
    parameters: 'Left lateral positioning; magnesium 4–6 g load per guideline; benzos if recurrent seizure',
    success: 'Seizure stopped; BP trend controlled toward safe range',
  },
  {
    id: 'PROC_GUIDELINE_ENVENOMATION',
    name: 'Bites / envenomation (including field irrigation)',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Snakebite', 'Marine sting', 'Insect sting with systemic reaction'],
    contra: ['Tourniquet or ice for pit viper bite contraindicated per modern tox care'],
    equipment: ['Immobilize limb', 'Pressure immobilization only when protocol indicates species', 'Epi for anaphylaxis'],
    parameters: 'Dead reptile photo; mark swelling; venom extraction kits discouraged',
    success: 'Systemic symptoms treated; rapid transport to antivenom center when indicated',
  },
  {
    id: 'PROC_GUIDELINE_CCB_OVERDOSE',
    name: 'Calcium channel blocker overdose management',
    category: 'Medical',
    minLevel: 'PARAMEDIC',
    ind: ['Hypotension bradycardia with CCB history', 'Hyperglycemia clue'],
    contra: ['None for calcium in suspected CCB overdose with shock'],
    equipment: ['Calcium salts', 'Glucagon', 'Insulin/euglycemia adjunct if protocol', 'Pressors'],
    parameters: 'Calcium chloride or gluconate boluses; pacing; lipids if high-dose verapamil/dilt',
    success: 'BP and HR trend improved',
  },
  {
    id: 'PROC_GUIDELINE_BETA_BLOCKER_OD',
    name: 'Beta blocker overdose management',
    category: 'Medical',
    minLevel: 'PARAMEDIC',
    ind: ['Bradycardia hypotension with BB ingestion'],
    contra: ['Glucagon contraindicated in pheo/insulinoma'],
    equipment: ['Glucagon', 'Calcium', 'Pacing pads', 'Pressors'],
    parameters: 'High-dose glucagon bolus then infusion; consider lipid emulsion per tox',
    success: 'Perfusion improves with vasoactive support',
  },
  {
    id: 'PROC_GUIDELINE_STIMULANT_TOXICITY',
    name: 'Stimulant poisoning / excited delirium support',
    category: 'Medical',
    minLevel: 'PARAMEDIC',
    ind: ['Hyperthermia agitation', 'Sympathomimetic toxidrome'],
    contra: ['Physical restraint without sedation plan'],
    equipment: ['Sedation', 'Cooling', 'Monitor', 'Law enforcement coordination'],
    parameters: 'Benzodiazepines first line; active cooling; watch CK/rhabdo',
    success: 'Calm cooperative patient; core temp falling',
  },
  {
    id: 'PROC_GUIDELINE_TOPICAL_CHEMICAL_BURN',
    name: 'Topical chemical burn decontamination',
    category: 'Trauma',
    minLevel: 'EMT',
    ind: ['Skin chemical exposure', 'HF acid splash'],
    contra: ['Powder chemicals—brush off before irrigation'],
    equipment: ['Water irrigation', 'HF calcium gluconate gel if protocol'],
    parameters: 'Prolonged irrigation; remove contaminated clothing; protect crew',
    success: 'Pain decreases; pH normalized when measurable',
  },
  {
    id: 'PROC_GUIDELINE_RADIATION',
    name: 'Radiation exposure field response',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Known radiation incident', 'Radioactive contamination on scene'],
    contra: ['Entering hot zone without dosimetry'],
    equipment: ['PPE', 'Decon corridor setup', 'KI tablets if public health Mass Dispensing'],
    parameters: 'Time-distance-shielding; remove outer garments; nasal swabs at hospital',
    success: 'Patient decontaminated; providers stay below exposure limits',
  },
  {
    id: 'PROC_GUIDELINE_NERVE_AGENT',
    name: 'Acetylcholinesterase inhibitor / nerve agent exposure',
    category: 'Medical',
    minLevel: 'PARAMEDIC',
    ind: ['SLUDGE findings after known exposure', 'Organophosphate suspected'],
    contra: ['Delay antidote in severe toxicity'],
    equipment: ['Atropine', 'Pralidoxime', 'Mark I / DuoDote auto-injectors', 'PPE'],
    parameters: 'Repeat atropine until secretions dry; 2-PAM early',
    success: 'Ventilation easier; secretions reduced',
  },
  {
    id: 'PROC_GUIDELINE_RIOT_AGENT',
    name: 'Riot control agent exposure care',
    category: 'Medical',
    minLevel: 'EMT',
    ind: ['Tear gas / RC agent symptoms', 'OC spray exposure'],
    contra: ['Asthma may flare—monitor closely'],
    equipment: ['Saline irrigation', 'O2', 'Albuterol'],
    parameters: 'Fresh air; skin decon; remove contact lenses',
    success: 'Eye and respiratory symptoms improve',
  },
  {
    id: 'PROC_GUIDELINE_RESPIRATORY_IRRITANT',
    name: 'Inhalational irritant / chemical airway injury',
    category: 'Airway',
    minLevel: 'EMT',
    ind: ['Chlorine / ammonia exposure', 'Industrial inhalation'],
    contra: ['Enter confined space without HAZMAT clearance'],
    equipment: ['O2', 'BVM', 'CPAP if authorized', 'MARCHE'],
    parameters: 'Humidified O2; bronchospasm treat like asthma; observe delayed pulmonary edema',
    success: 'SpO2 maintained; wheeze improved',
  },
  {
    id: 'PROC_GUIDELINE_DIVE_INJURY',
    name: 'Dive / scuba injury and decompression illness',
    category: 'Medical',
    minLevel: 'PARAMEDIC',
    ind: ['Neuro deficit after ascent', 'Painful joints post-dive', 'SOB after diving'],
    contra: ['Do not return to depth without hyperbaric consultation'],
    equipment: ['High-flow O2', 'Monitor', 'IV NS'],
    parameters: '100% O2; IV fluid; transport to hyperbaric-capable facility',
    success: 'Symptoms stabilize or improve with O2 en route',
  },
  {
    id: 'PROC_GUIDELINE_TASER',
    name: 'Conducted electrical weapon (CEW) injury assessment',
    category: 'Trauma',
    minLevel: 'EMT',
    ind: ['Post-CEW agitated patient', 'Fall secondary to CEW', 'Dart in sensitive area'],
    contra: ['Prolonged restraint after CEW without assessment'],
    equipment: ['Monitor', 'Dart removal per policy'],
    parameters: 'Assess for rhabdomyolysis, acidosis; evaluate traumatic fall injuries',
    success: 'Rhythm stable; wounds managed; sedation if still combative',
  },
  {
    id: 'PROC_GUIDELINE_LIGHTNING',
    name: 'Lightning strike resuscitation',
    category: 'Trauma',
    minLevel: 'EMT',
    ind: ['Lightning strike victim apneic or pulseless', 'Keraunoparalysis'],
    contra: ['Assume simultaneous triage—reverse triage if mass strike'],
    equipment: ['AED', 'BVM'],
    parameters: 'Aggressive BLS/ALS; prolonged resuscitation may succeed in lightning arrest',
    success: 'ROSC or organized termination after extended effort if indicated',
  },
  {
    id: 'PROC_GUIDELINE_MASS_CASUALTY',
    name: 'Trauma mass casualty triage',
    category: 'Trauma',
    minLevel: 'EMT',
    ind: ['Multiple critical patients', 'Resources overwhelmed'],
    contra: ['Transport order chaos—use triage tags'],
    equipment: ['Triage tags', 'MCI kits', 'Communications'],
    parameters: 'START/JumpSTART per jurisdiction; designate transport officer',
    success: 'Most survivors matched to correct transport capacity',
  },
  {
    id: 'PROC_GUIDELINE_HIGH_THREAT',
    name: 'High threat / warm zone casualty care',
    category: 'Trauma',
    minLevel: 'EMT',
    ind: ['Active threat paused', 'Tactical medicine phase'],
    contra: ['Care in cold zone only until secure'],
    equipment: ['Ballistic PPE', 'Hemorrhage control', 'IFAK counterpart'],
    parameters: 'Self-aid/buddy-aid; limited interventions; rapid extraction',
    success: 'Casualty moved to casualty collection point alive',
  },
];

